Dataset:
  data_set_name: ATIS
  train_path: ../dataset/ATIS/train.json
  test_path: ../dataset/ATIS/test.json
  batch_size_train: 64
  batch_size_valid: 128
  batch_size_test: 128
  portion: 0.10
Training:
  project_name: Bert_project
  optimizer: adam
  num_epochs: 200
  eval_path: ""
  dropout: 0.1
  slot_loss_coef: 1
  lr: 5e-5
  adam_epsilon: 1e-8
  weight_decay: 0
  warmup_steps: 0
  gradient_accumulation_steps: 1
  clip: 5
  patience: 10
  schedular_gamma: 0.5
  seed: 5
  save_every: 1
  decay_epoch: 4
  run_name: Bert_1D
  tag: Final_model
  watch_wandb: True
  wandb: True
  activate_crf: False
Model:
  seq_length: 50
  pad_id: 0